Repository seung-lab/connected-components-3d, pull requests merged in 2021-11, with the labels that each got.

#78 Add Linux aarch64 Wheel Built Support
  .github/workflows/build_wheel.yml
Labels: installation

#80 feat: Continuous value CCL for direct application to microscopy images
  MANIFEST.in
  README.md
  automated_test.py
  cc3d.cpp
  cc3d.hpp
  cc3d.pyx
  cc3d_continuous.hpp
Labels: feature

#81 perf: improve speed of 26, 4, and 8 connected continuous labeling
  cc3d_continuous.hpp
Labels: performance

#82 perf: faster continuous CCL for signed types
  benchmarks/README.md
  benchmarks/benchmarks.py
  cc3d_continuous.hpp
Labels: performance
